### PR TITLE
Hector branch

### PR DESCRIPTION
**Pull request by Hector-Alexander-Lopez**
Attempting merge

### CODE REVIEW

**Review by Hector-Alexander-Lopez — COMMENTED** [review]
attempting merge

**Review by Hector-Alexander-Lopez — COMMENTED** [review]
Resolving Conflicts

**Review by Hector-Alexander-Lopez — COMMENTED** [review]
Correcting for conflicts

**Review by Hector-Alexander-Lopez — COMMENTED** [review]
Please review, I don't see any conflicts in the HTML

**Review by portfedh — APPROVED** [review]

**Pull request merged**
